Don't compact arrays
nuts-foundation/go-did pull request #98
Opened 2023-11-29 09:55 UTC by reinkrul

This makes it hard to predict what the marshalled JSON object will look like, meaning things like creating presentation submissions will be harder. E.g., input descriptor mapping path can be indexed or not, depending on the number of VCs in the VP.

We also incorrectly applied the principal to serviceEndpoint, fixed that as well.

We should still support parsing compacted arrays, of course.

2023-11-30 12:00 UTC, gerardsn requested changes
Does this break validation, signature checking, etc. on existing docs/VC/VP?

2023-11-30 13:38 UTC, gerardsn commented
> Does this break validation, signature checking, etc. on existing docs/VC/VP?

is that a no?

2023-12-01 07:37 UTC, reinkrul commented
> > Does this break validation, signature checking, etc. on existing docs/VC/VP?
> 
> is that a no?

Now I think of it, we need to check whether JSON-LD signature validation now fails. If existing VCs are unmarshalled/marshalled again using the `MarshalJSON` methods, the signature might change (since a compacted array became uncompacted).

2023-12-01 08:33 UTC, woutslakhorst commented
> Now I think of it, we need to check whether JSON-LD signature validation now fails. If existing VCs are unmarshalled/marshalled again using the MarshalJSON methods, the signature might change (since a compacted array became uncompacted).

The signature is computed over quads. The quads for an object or array of size 1 are the same. So "should" be ok.

2023-12-01 08:38 UTC, woutslakhorst approved these changes

2023-12-01 09:12 UTC, merged